name: Activate the EMH
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  start-conversation:
    name: Start Conversation
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 I'm a doctor, not an engineer.
        uses: actions/checkout@v2
      - name: 🐍 I'm a doctor, not a zookeeper.
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: 📦 I'm a doctor, not a database.
        run: |
          python -m pip install -r requirements.txt
      - name: 🥼 Please state the nature of the medical emergency!
        env:
          MONGODB_CONNECTION_STRING: ${{secrets.MONGODB_CONNECTION_STRING}}
          REDDIT_PASSWORD: ${{secrets.REDDIT_PASSWORD}}
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
        run: |
          python -m src.startConversation
  looking-for-quotes:
    name: Looking for qoutes
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 I'm a doctor, not an engineer.
        uses: actions/checkout@v2
      - name: 🐍 I'm a doctor, not a zookeeper.
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: 📦 I'm a doctor, not a database.
        run: |
          python -m pip install -r requirements
      - name: 🥼 Please state the nature of the medical emergency!
        env:
          MONGODB_CONNECTION_STRING: ${{secrets.MONGODB_CONNECTION_STRING}}
          REDDIT_PASSWORD: ${{secrets.REDDIT_PASSWORD}}
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
        run: |
          python -m src.lookForMoreQuotes
